<?php
$this->headLink()->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
                 ->appendStylesheet('/assets/colorbox/colorbox.css');

$this->headScript()->appendFile('/assets/data-tables/jquery.dataTables.js')
                   ->appendFile('/assets/data-tables/DT_bootstrap.js')
                   ->appendFile('/assets/colorbox/jquery.colorbox-min.js');

$this->inlineScript()->appendScript(<<<EOS
   
jQuery(document).ready(function() {	
    $(".iframe").colorbox({ iframe:true, width:"80%", height:"80%", fastIframe:false });

    $('#plants').dataTable({
        "sDom": "<'row-fluid'<'span6'i><'span6'f>r>t<'row-fluid'<'span6'l><'span6'p>>",
        "bStateSave": true,
        "sPaginationType": "bootstrap",
        "oLanguage": {
            "sLengthMenu": "_MENU_ records per page",
            "oPaginate": {
                "sPrevious": "Prev",
                "sNext": "Next"
            },
        "sUrl": "/assets/data-tables/language/it_IT.txt"
        },
        "aoColumnDefs": [{
            'bSortable': false,
            'aTargets': [3]
        }]
    });
});

EOS
);

?>

<div class="row-fluid">
   <div class="span12">
        <h3 class="page-title">Gestione utenti</h3>
    </div>
</div>

<?php echo $this->DisplayFlash($this->flashMessages); ?>

<div class="row-fluid vspacer20">
    <div class="span12">
        <a class='iframe btn red' href="<?php echo $this->url('users',array('action'=>'new')); ?>"><i class="icon-plus"></i> Aggiungi utente</a>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered" id="plants">
            <thead>
                <tr>
                    <th>Nome</th>
                    <!--<th>Ditta</th>-->
                    <th>Abilitato</th>
                    <th>Ruolo</th>
                    <th>Azione</th>
                </tr>
            </thead>
                <tbody>
                    <?php
                    foreach($this->users as $I_user) :
                    ?>
                    <tr class="odd gradeX">
                        <td><?php echo $I_user->getName(); ?></td>
                        <!--<td><?php echo $I_user->getCompany(); ?></td>-->
                        <td>
                            <?php 
                                echo $this->boolToSiNo($I_user->getIsenabled()); 
                                echo '&nbsp';
                                echo $this->displayEnableLink($I_user->getId(),$I_user->getIsenabled()); 
                            ?>
                        </td>
                        <td><?php echo $I_user->getRole()->getName(); ?></td>
                        <td>
                            <a class="iframe" href="<?php echo $this->url('users',array('action'=>'edit','id'=>$I_user->getId())); ?>"><span class="icon-size"><i class="icon-edit"></i></span></a>
                            <?php /*
                            <a onClick="return confirm('Sicuro di voler cancellare <?php echo $I_user->getName(); ?>?');" href="<?php echo $this->url('users',array('action'=>'delete','id'=>$I_user->getId())); ?>"><span class="icon-size"><i class="icon-remove"></i></span></a>
                            */ ?>
                        </td>
                    </tr>
                    <?php
                    endforeach;
                    ?>
                </tbody>
        </table>
    </div>
</div>