<?php

namespace Users\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{

    /**
     * Get distinct roles except superadmin
     * 
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getRoles(){
        $s_query = 'SELECT r ' .
                   'FROM \Users\Entity\role r ' .
                   'WHERE r.isvisible = true ' . 
                   'ORDER BY r.name';
        $I_query = $this->getEntityManager()->createQuery($s_query);
       
       return $I_query->getResult();
    }
    
    public function getAllRoles(){
        $I_roles = $this->createQueryBuilder('Role')
            ->distinct('name')
            ->getQuery()
            ->execute();
        return $I_roles;
    }

    public function getAvailableUserRoles(){
        $s_query = 'SELECT r ' .
                   'FROM \Users\Entity\role r ' .
                   'WHERE r.id <> ' . \Users\Entity\Role::GUEST .
                   'ORDER BY r.name';
        $I_query = $this->getEntityManager()->createQuery($s_query);
       
       return $I_query->getResult();
    }
    
}