<?php

namespace Users\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SystemuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemuserRepository extends EntityRepository {
    
    public function getAllUsers(){
        $s_query = 'SELECT u ' .
            'FROM \Users\Entity\systemuser u ' .
            'WHERE u.isvisible = true ' .
            'ORDER BY u.name';
        $I_query = $this->getEntityManager()->createQuery($s_query);
         
        return $I_query->getResult();
    }
    
}
